import Link from "next/link";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <main>
          <nav style={{ marginBottom: "20px", display: "flex", gap: "10px" }}>
            <Link href="/" style={{ margin: 0 }}>
              Home
            </Link>
            <Link href="/notes" style={{ margin: 0 }}>
              Notes
            </Link>
          </nav>
          {children}
        </main>
      </body>
    </html>
  );
}
